In [10]:
import numpy as np
x_train = np.array([[1,1,1], [2,2,2], [3,3,3], [4,4,4], [5,5,5]])
X = np.array([[1,2,3], [4,5,6]])
p=3
def minkowski_distance(x1, x2, axis=None):
        return np.power(np.sum(np.power(np.abs(x1 - x2), p), axis=axis), 1/p)

distances = minkowski_distance(x_train, X[:, np.newaxis], axis=2)
print(distances)

[[2.08008382 1.25992105 2.08008382 3.30192725 4.62606501]
 [6.         4.62606501 3.30192725 2.08008382 1.25992105]]


In [12]:
k = 2
y_train = np.array([1, 1, 2, 3, 100])
sorted_indices = np.argsort(distances, axis=1) # Sorts the indices of the distances matrix column in each row (test points), in ascending order.
print(sorted_indices)
k_nearest_indices = sorted_indices[:, :k] # Takes the k nearest neighbors for each test point.
print(k_nearest_indices)
k_nearest_labels = y_train[k_nearest_indices]
print(k_nearest_labels)

[[1 0 2 3 4]
 [4 3 2 1 0]]
[[1 0]
 [4 3]]
[[  1   1]
 [100   3]]


In [13]:
def tie_breaking(labels):
        unique, counts = np.unique(labels, return_counts=True)
        return unique[np.argmax(counts)]
predictions = np.apply_along_axis(tie_breaking, axis=1, arr=k_nearest_labels)
print(predictions)

[1 3]


In [17]:
np.sum(np.array([5,10,3,5])==10)

1

In [ ]:
if len(unique_labels) == 2 and counts[0] == counts[1]:
    # Tie-breaking based on distance to the nearest neighbor
    distances = euclidean_distances(self.X_train[labels == unique_labels[0]], [self.X_train[0]])
    min_distance_index = np.argmin(distances)
    return unique_labels[min_distance_index]